name: build and push native image

on:
    push:
        branches: [main]
        paths:
            - "src/**"
            - "pom.xml"
            - ".github/workflows/**"
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/web-app-serverside-native

        steps:
            - uses: actions/checkout@v4

            # Setup Node.js for Tailwind
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install Node dependencies
              run: npm install

            - name: Build Tailwind CSS
              run: npm run tw:build

            # Setup Java for Quarkus
            - name: Setup Java 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"
                  cache: "maven"

            - name: Make Maven wrapper executable
              run: chmod +x mvnw

            - name: Build native binary with Quarkus (containerized)
              run: ./mvnw package -Pnative -Dquarkus.native.container-build=true

            - name: Login to Docker Hub
              if: ${{ github.ref == 'refs/heads/main' }}
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push Docker Image
              if: ${{ github.ref == 'refs/heads/main' }}
              run: |
                  IMAGE_TAG=${GITHUB_SHA::7}
                  docker build -f src/main/docker/Dockerfile.native -t $DOCKER_IMAGE_NAME:$IMAGE_TAG -t $DOCKER_IMAGE_NAME:latest .
                  echo "Pushing image $DOCKER_IMAGE_NAME:$IMAGE_TAG"
                  docker push $DOCKER_IMAGE_NAME:$IMAGE_TAG
                  docker push $DOCKER_IMAGE_NAME:latest
